site_name: "Unguided Cerebral Organoid Protocol"

nav:
  - Home: index.md
  - Introduction: index.md#introduction
  - Materials & Equipment: index.md#materials-and-equipment
  - Protocol: index.md#detailed-protocol
  - Appendix A: index.md#appendix-a
  - Appendix B: index.md#appendix-b
  - Image Gallery: index.md#image-gallery

theme:
  name: material
  logo: images/logo_new.png
  favicon: images/favicon.png
  features:
    - navigation.expand
    - navigation.top
    - navigation.sections
    - toc.integrate
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - header.autohide
    - announce.dismiss
  palette:
    # Custom palette with blue/cyan for science
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: "Inter"
    code: "JetBrains Mono"
  language: en

plugins:
  - search
  - social
  - tags
  - table-reader

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourrepo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourtwitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/yourtelegram